language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g typescript karma-cli grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install
  - tsc

script:
 - karma start karma.sauce.conf.js

after_success:
  - grunt coveralls

env:
  global:
    - secure: dKnKQ4USOx4z5J5T7IABDHKSJeogk5UFWAJMKxkNkmkWp/hN1uuTrN7tgZ7frn39zW8kd++Z2HXSevC77MdZqtEZ4VCNfYdBuajj2da9j+/obTBdIH5BAYjcVGSJP1cPGPlbxwowjGyz/iujoVSsuDpL5rAyQTNKAsQjauKO1y0KALp5zfHzmNvJ8ysAKRJPI8KmFovw3ykLPZl2+R0B+1O4em/p/xzVMpZDoGu3hnlaE8whkT7Yc04x3nYKlA7NhkFidL5HdE98rjlO7i/krcOFV2xosBmoS9WzH9Y7w1oymZj3OXIm35Y8iYciqo1OJwNHNH1+Fpsa31nB2cGvcvcMhfznI1ltp7QhEU9iMN7AiAYCcqTh3xn7WCSKsmqkPC/2klHadDsNX0TB/2alM22aU6uABM/iKnQI55XfmQIjYf+8DaP6OPm/os3pue7x42lA7pkyodfMBAHP/oJli1WfLujcfVnMiblm+DvwMuqvUfN5CXqN3l7tcgweZZ768dUR5bduecE8zDhPMNj0ncBdLWbRlg3w42BBe2c9f13rYwWaHCta9TLI5sm/5Tg1rAL+hzp6NUjDFss4dLwOFJ6aGTtiTmbUrC2DsPf+bz5zB78lEU/NVkTDD0317Nsw47AYOoSqOofeFiXetM+warCr/MBSmF4mKr4j25k0b9o=
    - secure: d+D96CgA5/Uc7CT/ml+8odgs/3Uq291IZit4Zr1jlnc9BQQO+QwFSl06oT0S/UX3ihDdkv2LWF6+8BV06W0lHBS9JRO+wr/9fx4/cBNeC2Sp9sH/FevEpoueZjeOgeYyQdUyoWcKYCQoJw0TnZa3tnN8n7mZu6p3FY2SNVZ5ArVno0fgcaaGRu5ZXAbIJCij7ynCaMKqMYe/6c0KtIuEpr5/Z9RuM6AAewHTrXE7BP5mEUjuUR4RybhrrMeQUkcFEz1J3a2ynkN9YvT3w0lVVqu6uf0obF2ToEx1S+wxSN02XxXLdYrH0IfsyTDycTpwUS/1CeYf8j7kcu1oIULAucWCcOwawjoZIK0dSISkrycWxl4fVSkg29lM4uRTtxveedjJzvw4x7KiH1CerczQiQTSZ3EO7r1/NncGJyJTCLPYtEKDMNV2KtXxJh5UI2MD9YscwWYlN9g++tN290u4j6GQXsREu+YNuV4EQYVtYQVRSPxy2u/YS8Yi2NqstQBXaCByu/DN0tmnm970+CFHKRZLuw5nnYGdtdIn/K5vjKq3GBUkltnEP7Vei8rCAvuFR0xVFI3ecNybBFmZCJ/4S+mynsI7ftHTIqTFdULbejvOWz8Z+TV99lvQW3fNGdw429ayjg+bKTw8GSrW6EOtOaSQDtC8chnLcbwK/UqxrDk=
